--- 
language: node_js
env: 
  global: 
  - secure: |-
      U951/clicU/IsOoTXQPtcmDs4HKc1Nh9NwjSnqMkgcs60KqkWddIwi5tD/uG
      abzqVXgggDi350mtA5fLXvoFQuvqygFnBt174I33zEzN6j8ptf3YP+eatDB0
      vp2CMdUVp2f3X+oWC3/9RlggWRCNo9bxTu280ovhx6NXLDxm50Y=
after_success:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku plugins:install https://github.com/ddollar/heroku-anvil
  - heroku build -r rss-unify  -b https://github.com/heroku/heroku-buildpack-nodejs.git
node_js: 
- 0.8
